# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Soul Heart Grit
email: andrecab@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Coaching fitness and healthy lifestyle

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.soulheartgrit.com" # the base hostname & protocol for your site
twitter_username: andresolerc
github_username:  andresolerc
instagram_username: soulheartgrit

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal

permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-sitemap
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-127506011-1
    anonymizeIp: false
